language: python
python:
  - "3.4"
  - "3.5"

install: "pip install -r .travis.requirements"

script: ./run_tests.py

git:
    # Don't download all the submodules
    submodules: false

notifications:
    email:
        recipients:
            - blacklight86@gmail.com
        on_success: change
        on_failure: change

